# Generated by Django 6.0.2 on 2026-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('purchase_price', models.IntegerField(verbose_name='Цена покупки')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Цена продажи')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Дата продажи')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
