# Generated by Django 6.0.2 on 2026-02-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='items_expen_date_0ae283_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['purchase_date'], name='items_item_purchas_031305_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sale_date'], name='items_item_sale_da_84cf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='items_item_name_1c746e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['purchase_date', 'sale_date'], name='items_item_purchas_85485b_idx'),
        ),
    ]
