# Generated by Django 6.0.2 on 2026-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Непредвиденные расходы',
                'verbose_name_plural': 'Непредвиденные расходы',
                'ordering': ['-date'],
            },
        ),
    ]
