# Generated by Django 6.0.2 on 2026-02-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
