# Generated by Django 6.0.2 on 2026-02-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleshPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solovik', models.IntegerField(default=0, verbose_name='Мякоть солевика')),
                ('slastena', models.IntegerField(default=0, verbose_name='Мякоть сластёны')),
                ('kubarbuz', models.IntegerField(default=0, verbose_name='Мякоть кубарбуза')),
                ('limonnik', models.IntegerField(default=0, verbose_name='Мякоть лимонника')),
            ],
            options={
                'verbose_name': 'Цены закупки мякоти',
                'verbose_name_plural': 'Цены закупки мякоти',
            },
        ),
    ]
