# Generated by Django 6.0.2 on 2026-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_fleshprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleshprice',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='fleshprice',
            name='kubarbuz',
            field=models.IntegerField(default=0, verbose_name='Мякоть куборбуза'),
        ),
        migrations.AlterField(
            model_name='fleshprice',
            name='slastena',
            field=models.IntegerField(default=0, verbose_name='Мякоть сластены'),
        ),
    ]
