# Generated by Django 6.0.2 on 2026-02-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_fleshprice_comment_alter_fleshprice_kubarbuz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(db_index=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sale_price'], name='items_item_sale_pr_f0757a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sale_date', 'sale_price'], name='items_item_sale_da_0e69fa_idx'),
        ),
    ]
