# Generated by Django 6.0.2 on 2026-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_expense_date_alter_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название предмета')),
                ('price_24h', models.IntegerField(blank=True, null=True, verbose_name='Цена за сутки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Предмет для анализа цен',
                'verbose_name_plural': 'Предметы для анализа цен',
                'ordering': ['name'],
            },
        ),
    ]
