# Generated by Django 6.0.6 on 2026-08-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_priceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceItem',
        ),
    ]
